In [16]:
import numpy as np
c1 = np.array(list(range(1,11)))
print(c1)

[ 1  2  3  4  5  6  7  8  9 10]


In [17]:
c2 = np.arange(10,101,10)
print(c2)

[ 10  20  30  40  50  60  70  80  90 100]


In [18]:
from string import ascii_uppercase
c3 = np.array(list(ascii_uppercase))
print(c3)

['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R'
 'S' 'T' 'U' 'V' 'W' 'X' 'Y' 'Z']


In [19]:
import numpy as np
zeros = np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
ones = np.ones(10)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [21]:
print(c3.dtype)

<U1


In [22]:
random_arr = np.random.randint(1,6,size = 10)
print(random_arr)

[2 4 4 1 3 1 1 3 4 4]


In [23]:
ary = np.arange(10)
print(ary)

[0 1 2 3 4 5 6 7 8 9]


In [24]:
ary2 = np.array([0,1,2,3,4,5,6,7,8,9])
odd = ary2[ary2%2 ==1]
print(odd)

[1 3 5 7 9]


In [25]:
ary3 = np.array([0,1,2,3,4,5,6,7,8,9])
ary3[ary3 %2 == 1] = -1
print(ary3)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
